<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
	'test' => 'thu do ma',
/* ----- General ----- */
    'User ID' => 'Mã số người dùng',
    'Post ID' => 'Mã số bài viết',
    'Comment ID' => 'Mã số ý kiến',
    'Content' => 'Nội dung',
    'Status' => 'Tình trạng',
    'ID' => 'Mã số',
    
    
/* ----- Layout ----- */
    'Create New account' => 'Tạo tài khoản mới',
    'Search Topics' => 'Tìm kiếm',
    'Start New Topic' => 'Tạo chủ đề mới',
    'My Active Threads' => 'Những chủ đề nổi bật',
    'Categories' => 'Danh mục',
    
    
/* ----- Admin model ----- */
    'Admins manager' => 'Quản lý tài khoản Quản Trị Viên',
    'Admin list' => 'Danh sách quản trị viên',
    'Admin' => 'Quản Trị Viên',
    'create' => 'Tạo ',
    'Update' => 'Cập nhật',
    'Username' => 'Tài khoản',
    'Password' => 'Mật khẩu',
    'First Name' => 'Tên',
    'Last Name' => 'Họ',
    'Has Admin Authority' => 'Có quyền Quản Trị',
    'Has User Authority' => 'Là người dùng',
    'Has Deal Authority' => 'Tạo Deal',
    'Has Dashboard Authority' => 'Tạo bảng điều khiển',

/* ----- City model ----- */
    'Name' => 'Tỉnh/Thành phố',
    'Code' => 'Mã tỉnh/thành phố',
    'Zip' => 'Mã khu vực',

/* ----- Post model ----- */
    'Post list' => 'Danh sách Deal',
    'Title' => 'Tiêu đề',
    'Contact Number' => 'Điện thoại',
    'Store Address' => 'Địa chỉ cửa hàng',
    'Link' => 'Liên kết',
    'Discount Code' => 'Mã khuyến mại',
    'Is Owner' => 'Chủ cửa hàng',
    'Image' => 'Hình ảnh',
    'Deal Type' => 'Loại Deal',
    'Deal Begin Date' => 'Ngày bắt đầu',
    'Deal End Date' => 'Ngày kết thúc',
    
/* ----- Comment model ----- */
    'Create Datetime' => 'Thời gian tạo',
    'Is Approved' => 'Được phê duyệt',
    
/* ----- Deal Type model ----- */
    'Vietnames Name' => 'Tên tiếng Việt',
    'English Name' => 'Tên tiếng Anh',
    
/* ----- User model ----- */
    'Facebook Login ID' => 'Tài khoản Facebook',
    'Identifier' => 'Số CMND',
    'City ID' => 'Mã Tỉnh/Thành phố',
    'Address' => 'Địc chỉ',
    'Age' => 'Tuổi',
    'Avatar' => 'Hình đại diện',
    'Is Power User' => 'Là người dùng cao cấp',
    
/* ----- Create New Deal ----- */
    'Please choose deal type' => 'Chọn loại Deal',
    'Enter Topic Title' => 'Nhập tiêu đề',
    'Share on Social Networks' => 'Chia sẻ đến các mạng xã hội',
    'Who can see this' => 'Ai có thể xem',
    'Everyone' => 'Tất cả',
    'Only Friends' => 'Bạn bè',
    
    
    
];
