<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
	'test' => 'thu do ma',
/* Admin model */
    'Admins manager' => 'Quản lý tài khoản Quản Trị Viên',
    'Admin list' => 'Danh sách quản trị viên',
    'Admin' => 'Quản Trị Viên',
    'create' => 'Tạo ',
    'Update' => 'Cập nhật',
    'Username' => 'Tài khoản',
    'Password' => 'Mật khẩu',
    'First Name' => 'Tên',
    'Last Name' => 'Họ',
    'Has Admin Authority' => 'Có quyền Quản Trị',
    'Has User Authority' => 'Là người dùng',
    'Has Deal Authority' => 'Tạo Deal',
    'Has Dashboard Authority' => 'Tạo bảng điều khiển',

/* City model */
    'Name' => 'Tỉnh/Thành phố',
    'Code' => 'Mã tỉnh/thành phố',
    'Zip' => 'Mã khu vực'
    
    
    
    
];
